web:
    image: bfirsh/compose-mongodb-demo
    environment:
        - "MONGO_HOST=counter_mongo_1"
        - "constraint:node==swarm-node-01"
    ports:
        - "80:5000"
mongo:
    image: mongo
    environment:
        - "constraint:node==swarm-node-02"
